### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/scheme#208]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/scheme/issues/199)
- [ ] [Add key features](https://github.com/exercism/scheme/issues/200)
- [ ] [Add tags](https://github.com/exercism/scheme/issues/201)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/scheme/issues/202)
- [ ] [Update status of track](https://github.com/exercism/scheme/issues/206)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/scheme/issues/207)
- [ ] [Pass linting checks](https://github.com/exercism/scheme/issues/203)
- [ ] [Build Test Runner](https://github.com/exercism/scheme/issues/204)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/scheme/issues/205) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
